### ISSUE TITLE
Request: Service name(s) in the process column list

### ISSUE THREAD

**Issue by AltF5** [processhacker/processhacker#406]
Having the service name(s) (csv) in the process coumn list would be invaluable, more than just in the Services tab. In the process list, it would identify which services that process is hosting (if any) without having to hover over each. In particular it would be most useful when viewing the processes in the treeview.

dmex, could you make this happen, please?
Thank you in advance if so!!

**Comment by nanoant** [comment]
👍  It was looking to add such feature request, but then here we go.

If possible I would love to see distinction for "Service names", "Service display names", "Service file names" (NOTE: Plural since you can have multiple services under single `svchost.exe`.

**Comment by AltF5** [comment]
Yes, with the number of services in Windows 10, I get REALLY tired of hovering over ALL and trying to memorize their start order in the tree.

**Comment by dmex** [comment]
>  service name(s) (csv) in the process coumn list

The only problem is the performance cost from allocating multiple strings and building the list every second?

You can open the properties for the process and view the services tab which shows the running services inside that process?

![image](https://user-images.githubusercontent.com/1306177/56472881-74c3b180-6464-11e9-9a5a-a805cc9f463c.png)

**Comment by AltF5** [comment]
Hey dmex thx for coming in. Opening just isn’t the same, when desiring side-by-side quick comparison. It’s probably faster to hover over for the tooltip. I wonder if there could be some option / toolbar switch to populate this column or not. Win10 has brought about so many I really want to see which one(s) is represented by what process in the tree.

**Comment by AltF5** [comment]
> The only problem is the performance cost from allocating multiple strings and building the list every second?
> 
> You can open the properties for the process and view the services tab which shows the running services inside that process?
> 

dmex,  I I implemented this in my own environment within proctree.c and proctree.h.
Whats the best way to get this implemented into the main code base / to have you review? Do I upload my changes in these 2 files to my github and do some pull request?

LMK, thanks!

**Comment by nanoant** [comment]
@AltF5 Can you please try to create Pull Request against latest master, I am really eager to try it out. 🤓 Thanks!

**Comment by Aidolii** [comment]
If a service has multiple associated by it, it could just list the topmost one and then `& 1 more` or `& 2 more` or something. You could also make it list them in all in a comma'd list for those who want to expand their columns that far, but it'd mess up `Size all columns to fit`. An option to have it be a multi-columned entry when the parent process is collapsed would be good but probably difficult to implement.

**Comment by nanoant** [comment]
> The only problem is the performance cost from allocating multiple strings and building the list every second?

@tmex If I can propose a trade-off, if the process is `svchost.exe` and has only one service can we replace Name and Description with service's Name (but not DLL) and Description?

If we don't want this as a default, this can be enabled via some new setting at Option > General, e.g. _"Replace svchost.exe Name and Description with single service"_ or something similar.

I guess it will make most of us happy working on recent >Win10 machines. Also, this does not require allocating anything.

WDYT?

**Comment by jerkstorecaller** [comment]
> The only problem is the performance cost from allocating multiple strings and building the list every second?

Hi @dmex, since the list of services is fixed, would it not be possible to create the string list once and then reuse it based on whatever identifier Windows has for the service?

But even with constant string recreation, this can be hidden behind an option flag until it's optimized later. "Replace svchost with service name (may incur performance penalty)". I'd use it, 100 strings per second is nothing on a machine capable of running Windows.

> You can open the properties for the process and view the services tab which shows the running services inside that process?

This doesn't show CPU/RAM/disk usage, which is the main reason I use Process Hacker. I wanna know what's using my system's resources. Right now Process Hacker is falling behind Task Manager by not listing services individually.

**Comment by dmex** [comment]
> Whats the best way to get this implemented into the main code base / to have you review? Do I upload my changes in these 2 files to my github and do some pull request?

@AltF5 

You can submit a PR for review.

> can we replace Name and Description with service's Name (but not DLL) and Description?

@nanoant 

The name column has a cache and replacing the strings would force a cache rebuild each second defeating the purpose of caching those entries and tanking the UI performance.

> since the list of services is fixed, would it not be possible to create the string list once and then reuse it based on whatever identifier Windows has for the service?

@jerkstorecaller 

Services are not fixed and are added/removed dynamically at runtime. Trying to synchronize the changes across multiple providers and multiple treelists only causes more issues than it solves - I've tried - the processes list isn't designed for services which is why services are located on a dedicated services window separate from the processes window and uses a separate thread and separate provider.

> Process Hacker is falling behind Task Manager by not listing services individually.

That's one reason why Task Manager performance sucks so bad and takes ages to startup.

Services are essentially DLLs running inside another process and the SCM functions are built on TCP style RPC calls. When you're using a .5s refresh internal that 500ms (or more) goes entirely on updating the service information preventing any other features from working - essentially the SCM doesn't play nice, causes major performance problems and was separated from other dialogs.

There are already 7 different windows in Process Hacker including an entire tab/tree showing individual service information and trying to shove more of that info onto the processes list means having to sacrifice a lot for little benefit. Ideally you should be using the existing dialogs and windows more effectively which give more information, more utility and are more reliable.

**Comment by jerkstorecaller** [comment]
@dmex , I'm sure different people use PH for different reasons, but for me, the reason I installed PH is to be able to answer the question "why is my computer slow all of a sudden?". Which translates to the combo "What things are running on my computer" and "How much resources is each thing using".

Task Manager already tells me "what is running on my computer" and "how much is it using", I didn't need PH for that.

What's great about PH is that it adds per-process CPU and I/O history on top of this, allowing me to answer the above questions, as well as "what made my computer slow 30 seconds ago, but by the time I opened Task Manager everything was fine again?".

PH fails at this task when it comes to services. I can't tell whether it's Logitech or Oracle's crappy update service that's slowing my PC down, or one of Microsoft's optional services. Basically it's saying "if a service is hogging your resources, PH can't help you identify it, it only helps if it's a regular process".

Right now, Task Manager is superior to PH if the culprit is a service, because it splits the 200 services into individual names. But, no historical data, so I can't investigate temporary slowdowns.

I know there's fancy sysadmin tools for system instrumentation and whatever, but I'm just a desktop user.

If there's a way to tell which service slowed down my system 30 seconds ago with PH, then I missed it, please tell me how.

**Comment by dmex** [comment]
> Task Manager 

Try resizing one of the columns back and forth and watch the entire UI bounce around like a yoyo from 1993:

![image](https://user-images.githubusercontent.com/1306177/103575292-9a893680-4f25-11eb-9b23-4875d9e58cfc.png)

It's even worse over RDP without a dedicated graphics driver. The column headers are not even hooked up to any values in the columns for processes and are just showing the system totals without counting the column values.... It also doesn't show the correct names for services and just picks one at random:

![image](https://user-images.githubusercontent.com/1306177/103575641-24d19a80-4f26-11eb-95e9-28b08e94b9ee.png)

It might look fancy but it barely works and the performance is so bad they've boxed themselves in and now can't do anything else with that window in the future without a complete rewrite from scratch... The code needed to mash those concepts/objects together prevents any optimization and is the main reason why TM can't include other features because that one feature eats up all the performance and also why TM doesn't have any real-time search features like PH does.

A service is literally just 1 DLL loaded in a process out of dozens of other non-service DLLs. The design and concept of services are entirely different to processes and provide minimal information. There isn't a way to show individual service utilization for IO/Memory/Disk etc... those statistics are only recorded for the process not the services because of the way they've been designed by Microsoft.

We've put services and processes as close together as possible in as many places as possible but both together on the processes list - as cool as it would be - is a bad idea.

> I can't tell whether it's Logitech or Oracle's crappy update service that's slowing my PC down, or one of Microsoft's optional services. Basically it's saying "if a service is hogging your resources, PH can't help you identify it, it only helps if it's a regular process".

It does but are you using any of these features?

Menus:
![image](https://user-images.githubusercontent.com/1306177/103577740-70d20e80-4f29-11eb-9b82-f34415e67112.png)

Tooltips:
![image](https://user-images.githubusercontent.com/1306177/103452171-8b856700-4d20-11eb-97d2-12e6eb39b1c6.png)

Threads:
![image](https://user-images.githubusercontent.com/1306177/103452196-cab3b800-4d20-11eb-9a0e-b384ff229b63.png)

Services:
![image](https://user-images.githubusercontent.com/1306177/103452183-a48e1800-4d20-11eb-9251-238dec0e64e3.png)

There's even an entire tab on the main window dedicated to just services:
![image](https://user-images.githubusercontent.com/1306177/103577913-c0183f00-4f29-11eb-98ef-e22d08328b5a.png)


> If there's a way to tell which service slowed down my system 30 seconds ago with PH, then I missed it, please tell me how.

You double click the graphs to view the process then click properties to view the services:

![image](https://user-images.githubusercontent.com/1306177/103578940-8f390980-4f2b-11eb-8e35-50bdb538df23.png)

**Comment by AltF5** [comment]
Hello there. Sorry I never saw the comment about doing a Pull Request. 

@dmex Would this still be entertained to implement these service strings as a column? I find it very useful in my modification build .
