### ISSUE TITLE
ProcessHacker GPU usage not working

### ISSUE THREAD

**Issue by BrendanatorX** [processhacker/processhacker#637]
So, long story short, I was on the up to date original 2.39? stable build, gpu counter used to work for me up til a few months ago and now it doesn't, brought it up with a friend who suggested swapping to the nightly build, so I did that.
Still not working properly though even on nightly.
I have the GPU monitoring extended tools turned on, I have Process Hacker running as admin with kernal driver, I've tried per some other user's forum posts reinstalling nvidia drivers, but it's still occurring.
I saw another person's similar issue with gpu monitoring here recently and a settings.xml was mentioned, but I don't even have that file.
Currently on Nightly 3.0.3147 (c46fddb8)
Win 10 Pro 64x
GTX 1060 6GB GPU and drivers up to date.
No other issues with Process Hacker that I'm aware of, I've tried to search for other people having same issue on github and googled other forums for fixes but just nothing concrete has come up or helped.
Edit: To be clear, by not working, I mean that the graphs and usage numbers only ever shows less than 5% usage compared to task manager or common sense running modern games at max settings. which should be pushing gpu usage up to 40-80%

**Comment by dmex** [comment]
> GTX 1060

What's the current version of nvidia installed?

**Comment by BrendanatorX** [comment]
V451.48 (release date 24th June 2020)
Though as I said, it's persisted through any and all nvidia updates for months.

**Comment by BrendanatorX** [comment]
Hoping this might be helpful..

I have now noticed that it does detect around 5% 'video decode' usage via Youtube on Firefox and stated it was from that, and around 1-2% on a different video player in firefox, however at that low percentage it couldn't tell me what it was from. So perhaps that's an indication that it works a little bit?
It's during gaming that really matters to me though, the '3D' node seems to get minimal usage, staying very low, mostly around 1-3% and not mention what is using it either. 

So I'm thinking this may in fact be an issue where it either doesn't have the right node(s) selected/available or isn't able to get the right information from said nodes.
One of the main changes I noticed from switching to nightly is that it only shows me 8 nodes (compared to 15) and tells me what each node is actually meant for eg. 3D, Video Decode, Overlay, VR, etc. since I was completely guessing what any of it meant on the stable build so I really appreciate this change. 

I remember when this feature was working on the stable build last year and even before that, that I would open up the node selection screen and notice that there were 15 nodes that all said the same thing and only one of them (node 9) would actually do anything during gaming so I turned them all off except that one node because otherwise it was creating an unrealistic average.
There was one time I saw momentary usage on node 11 as well on stable, though that could have been from something else, otherwise none of the nodes I had available then (stable) or now (nightly) seem to really detect much of anything during a game.

Anyway this does kinda remind me of the one comment I found mentioning nvidia drivers/registries how they had to reinstall nvidia driver several times until process hacker was able to find the right information. Though I have tried this and had no luck yet, hoping something will come out of this.
I may have to look into rivatuner temporarily since I've seen a lot of youtubers use that during games for performance checking, though Process Hacker is more what I'm looking for and I love it to bits, especially the Process Hacker 'tray icons' for cpu usage and gpu usage. 
(Currently the GPU Usage(text) and GPU History ones currently say %0.00 instead of GPU 0.00% like I expected they would, not sure if that's a bug or intentional)

**Comment by dmex** [comment]
> an issue where it either doesn't have the right node(s) selected/available or isn't able to get the right information from said nodes

v2.39 required users to manually select the gpu nodes for usage calculation but I removed this requirement in favour of what Task Manager does which is using the highest value from every node rather than each single node.

> One of the main changes I noticed from switching to nightly is that it only shows me 8 nodes (compared to 15)

Previous versions of Process Hacker included the BasicRender graphics device which is now excluded by default. It's a virtual device which doesn't get used unless you remove the physical graphics device driver so its nodes are no longer displayed.

> the GPU Usage(text) and GPU History ones currently say %0.00 instead of GPU 0.00% 

This was fixed in the latest nightly build.

> I have now noticed that it does detect around 5% 'video decode' usage 

Does the v2.39 stable build have the same GPU usage issue or just the nightly builds?

**Comment by BrendanatorX** [comment]
> This was fixed in the latest nightly build.

Ah sweet, glad to hear it! Auto-update is turned on though and nothing has happened regarding an update though, so a tad confused there, but all good.

> Does the v2.39 stable build have the same GPU usage issue or just the nightly builds?

Both stable and nightly have the same GPU usage issue.
It's because I had the issue on stable that I ended up on nightly build hoping something would be different.

**Comment by dmex** [comment]
> Auto-update is turned on though and nothing has happened regarding an update

The update check is once a week. You can force the update check using the Help menu > "Check for updates" window.

> Both stable and nightly have the same GPU usage issue.

Do both Task Manager and Process Explorer have the same issue?
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

Process Explorer and Process Hacker use the exact same API functions so if gpu usage is also not working for Process Explorer then it would be an issue with the nvidia driver.

Task Manager uses a sightly different method for gpu usage so if Task Manager does report the correct usage you can try manually change the "ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters" setting to 1 so that Process Hacker uses the same API as Task Manager for gpu usage.

**Comment by BrendanatorX** [comment]
In Process Explorer, the System Information window (and GPU Engines/Nodes window) both show no usage. Though Engine 11 does fluctuate around 1% when it should be much higher, this is similar to Process Hacker.

![image](https://user-images.githubusercontent.com/26519206/86357053-99dec180-bcb0-11ea-9a32-a64d598d554e.png)

However.. Process Explorer does show gpu usage in the processes list, and in the properties of a program.

![image](https://user-images.githubusercontent.com/26519206/86358241-80d71000-bcb2-11ea-9abd-564e9fdbf7ce.png)

It seems the information being called in these 2 different fashions are somehow different despite being related.

**Comment by BrendanatorX** [comment]
I will also note that I have also tried going into Nvidia Control Panel, unhidden developer settings and turned on 'allow access to GPU performance counters for all users' incase that somehow gave permissions to any necessary information to Process Hacker, but it didn't change anything whether it was on or off, even after PC/Process Hacker restarts.

Also the problem persists when Process Hacker is 'Run as Administrator' and also persists when the Process Hacker 'Kernel Driver' is on or off.

**Comment by dmex** [comment]
Have you also tried changing the `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` setting to 1?

**Comment by BrendanatorX** [comment]
I can't remember if I did or not, but if like you say that simply allows it to copy Task Manager, then I'd say it probably would have worked if I did. Though I prefer the sound of Process Hacker's performance counters using less resources to keep track of things. (which I think I read somewhere is the benefit over Task Manager)

In any case, in the process of fixing some other issues I've been having, last night I did a DDU Tool driver removal on safe mode, with microsoft/windows auto-updates and networking disabled, then reinstalled latest Nvidia Drivers/software again, followed by what I think is called an in-place-repair of windows? which reinstalled windows over the top of itself to fix anything it could fix.

I'm happy to report that I've just checked if anything had changed and discovered that Process Hacker now correctly detects usage on the 3D node while I have a game open, meaning my problem appears solved.

I'll leave leave this issue open temporarily just in case anything changes or it was a fluke.
However I do wonder if there is a specific cause which can still be targeted and fixed in case of future issues or anyone else with the same problem.
