### ISSUE TITLE
Toolbar contents disappear after dpi change on Windows 10

### ISSUE THREAD

**Issue by anvish** [processhacker/processhacker#69]
When changing Windows 10 scale, toolbar buttons disappear

![1](https://cloud.githubusercontent.com/assets/1114090/19596901/c0a2da4e-9799-11e6-9dc3-a876625d7ecc.png)

**Comment by dmex** [comment]
This might have already been fixed with other Toolbar changes some weeks ago... Have you tried the nightly builds?

https://wj32.org/processhacker/forums/viewtopic.php?f=8&t=2315

**Comment by anvish** [comment]
reproducible on nightly build
![2](https://cloud.githubusercontent.com/assets/1114090/19818671/700ed3d8-9d59-11e6-945b-093f2dedc488.png)

Steps:
start ProcessHacker
increase scale (say, from 200 to 250)
button items disappear
after scale restoration they remain hidden

**Comment by dmex** [comment]
> increase scale (say, from 200 to 250)

How do you increase the scale from 200 to 250 without Windows forcing you to logout? 

I've made some changes that should fix the DPI issues.. Can you please update to the latest nightly build and let me know if the DPI issues are fixed?

You can update using the Help > Check for updates menu or download the new build directly:
https://wj32.org/processhacker/nightly.php

**Comment by anvish** [comment]
@dmex Windows 10 doesn't force to log out.
The issue is still reproducible on 3.0.558

**Comment by dmex** [comment]
What type of screen do you have?

Windows 10 will only let me change the DPI up to 175 - anything above that requires me to use the 'custom scaling' option and logout after each change.

**Comment by anvish** [comment]
4K
